"""
PyMuPDF (fitz) table extraction service.

Uses PyMuPDF's native page.find_tables() API (available since v1.23.0).
This is a rule-based, coordinate-geometry approach that detects table
boundaries from vector graphics (drawn lines/borders) and text positions.
It requires no external models, has zero API cost, and runs entirely
locally.

Strategy selection logic:
  - "lines"        → for digital PDFs with bordered tables (most common
                     for commission statements)
  - "lines_strict" → for digital PDFs where background-coloured cells
                     cause false detections with the default strategy
  - "text"         → fallback for digital PDFs with borderless tables
                     that use whitespace alignment only

Note on scanned PDFs: PyMuPDF's find_tables() operates on the PDF's
internal vector graphics and text coordinate stream. It does NOT perform
OCR. A scanned PDF (is_digital=False) contains no selectable text or
vector lines — only a raster image. find_tables() will return zero tables
for any scanned document. This is expected and correct behaviour; it is
classified as tool_limitation in the runner, not as a failure.
"""

import logging
from pathlib import Path
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

try:
    import pymupdf
except ImportError:
    import fitz as pymupdf


class PyMuPDFService:
    """
    Extracts tables from PDF documents using PyMuPDF's native find_tables().

    Implements a three-strategy cascade for maximum recall on digital PDFs:
      1. "lines"        — primary: vector-graphics line detection
      2. "lines_strict" — secondary: ignore borderless background rects
      3. "text"         — tertiary: whitespace-based column/row inference

    Each strategy is tried independently; the strategy that finds the
    most non-empty tables is used as the final result. This approach is
    chosen because commission statements from different carriers use
    different table styling conventions — some use full borders, some
    use header-row shading only, and some use whitespace alignment alone.
    """

    # Default snap/join tolerance (points). PyMuPDF default is 3.
    # Slightly increased to handle minor line misalignments common in
    # PDFs generated by insurance billing software.
    SNAP_TOLERANCE: float = 3.5
    JOIN_TOLERANCE: float = 3.5

    # Minimum line length to consider as a table border (points).
    EDGE_MIN_LENGTH: float = 3.0

    def extract_tables(self, file_path: str) -> Dict[str, Any]:
        """
        Extract all tables from all pages of a PDF using PyMuPDF.

        Args:
            file_path: Absolute or relative path to the PDF file.

        Returns:
            {
                "tables": [
                    {
                        "headers": list[str],
                        "rows": list[list[str]],
                        "page_number": int,   # 0-based page index
                        "table_index": int,   # position on the page
                        "strategy_used": str, # which strategy found it
                        "bbox": tuple,        # (x0, y0, x1, y1) on page
                        "row_count": int,
                        "col_count": int,
                    },
                    ...
                ],
                "total_pages": int,
                "pages_with_tables": int,
                "tool": "pymupdf",
            }

        Raises:
            FileNotFoundError: if file_path does not exist.
            RuntimeError: if PyMuPDF cannot open the file.
        """
        path = Path(file_path)
        if not path.exists():
            raise FileNotFoundError(f"PDF not found: {file_path}")

        all_tables: List[Dict[str, Any]] = []
        pages_with_tables = 0

        try:
            doc = pymupdf.open(str(path))
        except Exception as exc:
            raise RuntimeError(
                f"PyMuPDF could not open {file_path}: {exc}"
            ) from exc

        total_pages = doc.page_count

        for page_num in range(total_pages):
            page = doc.load_page(page_num)
            page_tables = self._extract_page_tables(page, page_num)
            if page_tables:
                pages_with_tables += 1
                all_tables.extend(page_tables)

        doc.close()

        logger.info(
            "PyMuPDF: %d tables found across %d/%d pages in %s",
            len(all_tables),
            pages_with_tables,
            total_pages,
            path.name,
        )

        return {
            "tables": all_tables,
            "total_pages": total_pages,
            "pages_with_tables": pages_with_tables,
            "tool": "pymupdf",
        }

    def _extract_page_tables(
        self, page: Any, page_num: int
    ) -> List[Dict[str, Any]]:
        """
        Try all three strategies and return the best result for this page.

        "Best" = strategy that extracts the most tables with at least
        one non-empty data row. Ties are broken by the strategy order:
        lines > lines_strict > text.
        """
        strategies = ["lines", "lines_strict", "text"]
        best_tables: List[Dict[str, Any]] = []
        best_count = 0

        for strategy in strategies:
            try:
                candidate = self._try_strategy(page, page_num, strategy)
                # Count tables that have at least one data row
                non_empty = [
                    t for t in candidate if len(t.get("rows", [])) > 0
                ]
                if len(non_empty) > best_count:
                    best_count = len(non_empty)
                    best_tables = candidate
            except Exception as exc:
                logger.debug(
                    "PyMuPDF strategy '%s' failed on page %d: %s",
                    strategy,
                    page_num,
                    exc,
                )
                continue

        return best_tables

    def _try_strategy(
        self, page: Any, page_num: int, strategy: str
    ) -> List[Dict[str, Any]]:
        """
        Run find_tables() with a specific strategy and normalise results.
        """
        tabs = page.find_tables(
            strategy=strategy,
            snap_tolerance=self.SNAP_TOLERANCE,
            join_tolerance=self.JOIN_TOLERANCE,
            edge_min_length=self.EDGE_MIN_LENGTH,
        )

        results: List[Dict[str, Any]] = []

        for table_idx, table in enumerate(tabs.tables):
            raw_data = table.extract()
            # raw_data is a list of lists (rows × cols), including header row.
            # Cells may be None (merged spanning cells) — normalise to "".

            if not raw_data:
                continue

            # Determine header row using PyMuPDF's own header detection.
            # table.header.external = True  → header row is ABOVE the table
            #                                 (not in raw_data)
            # table.header.external = False → first row of raw_data is header
            if table.header.external:
                # Header text is above the table body in raw_data.
                # Use PyMuPDF's identified column names.
                header_names = [
                    str(n) if n is not None else ""
                    for n in table.header.names
                ]
                data_rows = raw_data  # all rows are data rows
            else:
                # First row of raw_data is the header.
                if len(raw_data) == 0:
                    continue
                header_names = [
                    str(c) if c is not None else ""
                    for c in raw_data[0]
                ]
                data_rows = raw_data[1:]  # remaining rows are data

            # Normalise all cells: None → "", strip whitespace.
            normalised_rows = [
                [
                    str(cell).strip() if cell is not None else ""
                    for cell in row
                ]
                for row in data_rows
            ]

            # Skip completely empty tables (all cells empty).
            all_empty = all(
                all(cell == "" for cell in row)
                for row in normalised_rows
            )
            if all_empty and all(h == "" for h in header_names):
                continue

            results.append(
                {
                    "headers": header_names,
                    "rows": normalised_rows,
                    "page_number": page_num,
                    "table_index": table_idx,
                    "strategy_used": strategy,
                    "bbox": tuple(table.bbox),
                    "row_count": table.row_count,
                    "col_count": table.col_count,
                }
            )

        return results
